// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace OrderManagementWebAPI.DTOs
{
    public partial class Labels
    {
        [Key]
        [JsonIgnore]
        public int LabelId { get; set; }
        public string LabelName { get; set; }
        public float Heigth { get; set; }
        public float Width { get; set; }
    }
}