// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderManagementWebAPI.DTOs
{
    public partial class OrderLabels
    {
        public int Id { get; set; }
        public int OrderNumber { get; set; }
        public string IdBoxNumber { get; set; }
        public int BoxNumber { get; set; }
        public int StartIndex { get; set; }
        public int StopIndex { get; set; }
        public int Quantity { get; set; }

        public virtual Orders OrderNumberNavigation { get; set; }
    }
}